# Generated by Django 5.1.1 on 2024-11-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_chrisdata_delete_comment_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chrisdata',
            name='post_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
