# Generated by Django 5.1.1 on 2024-12-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_otpverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='user',
        ),
        migrations.AddField(
            model_name='otpverification',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
