# Generated by Django 5.1.1 on 2024-12-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_otpverification_user_otpverification_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
